# add travi yml file for testing
language: java
dist: trusty
sudo: required

before_install:
- sudo apt-get install curl -y

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
- mvn clean package
- mkdir -p jar-folder
- cp target/*.jar jar-folder
- cp Dockerfile jar-folder
- export CLOUDSDK_CORE_DISABLE_PROMPTS=1
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
# Auth flow
- echo $GOOGLE_CREDENTIALS_BASE64 | base64 --decode > gcloud.p12
- gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.p12
- gcloud config set project spinnaker-poc-200412
# Push to Google container registry
- cd jar-folder
- gcloud container builds submit --tag gcr.io/spinnaker-poc-200412/travis-gradle-image .
